### PR TITLE
Fix mixed linefeeds

### PR DESCRIPTION
**Pull request by lboehm**
As discussed in Issue #115 I've opened this pull request to fix the issue with mixed line feeds. As this issue is only relevant for deployment I've added the code only in the `transpile` task and not also in `live-transpile` task. 

If you think, I should add it to `live-transpile` task, let me know.

### CODE REVIEW

**Comment by vobu** [comment]
cool shakes, thx already! and as you suggest, would you mind including in `live-transpile` as well. thanks!

**Comment by lboehm** [comment]
Yes, I'll add it on the weekend

**Comment by lboehm** [comment]
Hey :) I've added the commit for live transpile.

**Comment by vobu** [comment]
very cool, thx for your contribution!

**Pull request merged**
