### PR TITLE
feat(simpleproxy): Support configuration of proxied url parameters via .env and ui5.yaml 

### PR DESCRIPTION
**Pull request by marcelschork**
Implements the feature request described in [#428](https://github.com/petermuessig/ui5-ecosystem-showcase/issues/428).
Add missing docu for http headers.

### CODE REVIEW

**Comment by vobu** [comment]
@petermuessig any chance you can take a look?

**Comment by petermuessig** [comment]
Let me take a look into this later today after the daily business... 😃

**Review by petermuessig — APPROVED** [review]
LGTM - approved! 

@marcelschork : nice one! thanks for this contribution - I will release it soon.

**Comment by petermuessig** [comment]
@vobu - issue is fixed by you already - but change is not rebased yet. I submit and ignore the issue for now.

**Pull request merged**
