### PR TITLE
ui5-middleware-stringreplacer initial version

### PR DESCRIPTION
**Pull request by attila-boros**

### CODE REVIEW

**Comment by petermuessig** [comment]
Thanks for your PR. I will check and extend it asap.

**Comment by petermuessig** [comment]
Hi @attila-boros ,

just FYI - I am in the middle of a bigger refactoring for this code and the stringreplacer task to harmonize both and move them closer to the UI5 serveResources considering also the content type, the charset, ... It takes a bit more work for me and hopefully I can push a variant by end of this week...

BR,
Peter

**Comment by attila-boros** [comment]
Hi @petermuessig ,

Thanks for your update. This is a nice to have feature for me, and not urgent.

Best regards,
Attila

**Comment by petermuessig** [comment]
Thanks @attila-boros , good to know.

**Comment by petermuessig** [comment]
Closing in favor of PR https://github.com/petermuessig/ui5-ecosystem-showcase/pull/304

**Pull request closed without merging**
